title: Beckman Science Olympiad
description: Official site for the Beckman High School Science Olympiad team
baseurl: "" 
url: "https://beckman-high-school-science-olympiad.github.io"
theme: jekyll-theme-cayman

# GitHub Pages compatible themes: https://pages.github.com/themes/
