title: Beckman Science Olympiad
description: Official site for the Beckman Science Olympiad team
baseurl: ""
url: "https://<your-username>.github.io"

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

markdown: kramdown

minima:
  skin: custom